export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as PatientMainScreen } from './PatientScreens/PatientMainScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as CameraScreen } from './PatientScreens/CameraScreen'
export { default as ProfileScreen } from './PatientScreens/ProfileScreen'
export { default as ResultScreen } from './PatientScreens/ResultScreen'
export { default as DoctorsListScreen} from './PatientScreens/DoctorsListScreen'
export { default as AppointmentDetailScreen} from './PatientScreens/AppointmentDetailScreen'
// export { default as HistoryScreen} from './ArchivedScreens/HistoryScreen'
export { default as DetectionHistoryScreen } from './PatientScreens/DetectionHistoryScreen'
export { default as AppointmentHistoryScreen } from './PatientScreens/AppointmentHistoryScreen'
export { default as DoctorMainScreen } from './DoctorScreens/DoctorMainScreen'
export { default as ScheduleScreen } from './DoctorScreens/ScheduleScreen'
export { default as AddNewScheduleScreen } from './DoctorScreens/AddNewScheduleScreen'
export { default as MyAppointmentScreen } from './DoctorScreens/MyAppointmentScreen'
export { default as DoctorProfileScreen} from './DoctorScreens/DoctorProfileScreen'
