export { default as StartScreen } from './StartScreen'
export { default as PatientLoginScreen } from './PatientLoginScreen'
export { default as DoctorLoginScreen } from './DoctorLoginScreen'
export { default as PatientMainScreen } from './PatientMainScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as CameraScreen } from './CameraScreen'