export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as PatientMainScreen } from './PatientMainScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as CameraScreen } from './CameraScreen'
export { default as ProfileScreen } from './ProfileScreen'
export { default as ResultScreen } from './ResultScreen'
export { default as DoctorsListScreen} from './DoctorsListScreen'
export { default as AppointmentDetailScreen} from './AppointmentDetailScreen'
export { default as HistoryScreen} from './HistoryScreen'
export { default as DetectionHistoryScreen } from './DetectionHistoryScreen'
export { default as AppointmentHistoryScreen } from './AppointmentHistoryScreen'
export { default as DoctorMainScreen } from './DoctorMainScreen'
export { default as ScheduleScreen } from './ScheduleScreen'
export { default as AddNewScheduleScreen } from './AddNewScheduleScreen'
export { default as MyAppointmentScreen } from './MyAppointmentScreen'
