const ACTION_TYPES = {
    AUTH: {
        SIGN_IN: 'SIGN_IN',
        SIGN_OUT: 'SIGN_OUT',
        SIGNING_IN: 'SIGNING_IN',
        REFRESH_TOKEN: 'REFRESH_TOKEN'
    },
    DOCTOR: {
        UPDATE_PROFILE: 'DOCTOR_UPDATE_PROFILE',
        UPDATE_VERIFY_STATUS: 'UPDATE_VERIFY_STATUS',
        ADD_DOCTOR: 'ADD_DOCTOR'
    },
    DOCTOR_APPOINTMENT: {
        ADD_SCHEDULE: 'ADD_SCHEDULE',
        ADD_APPOINTMENT: 'DOCTOR_ADD_APPOINTMENT'
    },

    PATIENT: {
        UPDATE_PROFILE: 'PATIENT_UPDATE_PROFILE',
        ADD_PATIENT: 'ADD_PATIENT'        
    },
    RECORD: {
        ADD_RECORD: 'ADD_RECORD'
    },
    PATIENT_APPOINTMENT: {
        ADD_APPOINTMENT: 'PATIENT_ADD_APPOINTMENT'
    },
    DOCTOR_LIST: {
        FETCH_DOCTOR: 'FETCH_DOCTOR',
        FETCH_DOCTOR_SCHEDULE: 'FETCH_DOCTOR_SCHEDULE'
    }
}

export default ACTION_TYPES